version: '3.8'

services:
  # Dispositivos MIPS
  mips1:
    build:
      context: ./simulated-botnet/devices/mips
    container_name: mips1
    networks:
      botnet-net:
        ipv4_address: 172.20.0.2

  mips2:
    build:
      context: ./simulated-botnet/devices/mips
    container_name: mips2
    networks:
      botnet-net:
        ipv4_address: 172.20.0.3

  mips3:
    build:
      context: ./simulated-botnet/devices/mips
    container_name: mips3
    networks:
      botnet-net:
        ipv4_address: 172.20.0.4

  # Dispositivos ARM
  arm1:
    build:
      context: ./simulated-botnet/devices/arm
    container_name: arm1
    networks:
      botnet-net:
        ipv4_address: 172.20.0.5

  arm2:
    build:
      context: ./simulated-botnet/devices/arm
    container_name: arm2
    networks:
      botnet-net:
        ipv4_address: 172.20.0.6

  arm3:
    build:
      context: ./simulated-botnet/devices/arm
    container_name: arm3
    networks:
      botnet-net:
        ipv4_address: 172.20.0.7

  # Servidor C2
  c2server:
    build:
      context: ./simulated-botnet/c2
    container_name: c2server
    ports:
      - "8080:80"
    networks:
      botnet-net:
        ipv4_address: 172.20.0.8

  # Victim Ubuntu Container 
  victim1:
    image: ubuntu:20.04
    container_name: victim1
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    networks:
      botnet-net:
        ipv4_address: 172.20.0.10


  # Firmware Analysis: WNAP320
  firmadyne:
    build: ~/firmadyne
    privileged: true
    network_mode: "host"
    stdin_open: true
    tty: true

networks:
  botnet-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
