version: '3.8'

services:
  # MIPS Devices
  mips1:
    build:
      context: ./devices/mips
    container_name: mips1
    networks:
      - botnet-net

  mips2:
    build:
      context: ./devices/mips
    container_name: mips2
    networks:
      - botnet-net

  mips3:
    build:
      context: ./devices/mips
    container_name: mips3
    networks:
      - botnet-net

  # ARM Devices
  arm1:
    build:
      context: ./devices/arm
    container_name: arm1
    networks:
      - botnet-net

  arm2:
    build:
      context: ./devices/arm
    container_name: arm2
    networks:
      - botnet-net

  arm3:
    build:
      context: ./devices/arm
    container_name: arm3
    networks:
      - botnet-net

  # C2 Server
  c2server:
    build:
      context: ./c2
    container_name: c2server
    ports:
      - "8080:80"
    networks:
      - botnet-net

networks:
  botnet-net:
    driver: bridge
